SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_TITLE = "System Override"
TARGET_FPS = 60

GRAVITY = 9.8
PLAYER_MOVE_SPEED = 300
PLAYER_JUMP_SPEED = 600
PLAYER_MAX_X_SPEED = 400

CAMERA_PAN_SPEED = 0.1
CAMERA_ZOOM = 1.0

DATA_FILE_PATH = "data/game_data.json"
ASSETS_PATH = "assets"
