SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_TITLE = "System Override"
TARGET_FPS = 60

GRAVITY = 1.0
PLAYER_MOVE_SPEED = 6
PLAYER_JUMP_SPEED = 18
PLAYER_MAX_X_SPEED = 20
PLAYER_JUMP_HOLD_FRAMES = 10
PLAYER_JUMP_HOLD_FORCE = 1.2
PYMUNK_MOVE_SPEED = 240
PYMUNK_JUMP_IMPULSE = 1050
PYMUNK_MAX_VERTICAL_SPEED = 520

CAMERA_PAN_SPEED = 0.1
CAMERA_ZOOM = 1.0

DATA_FILE_PATH = "data/game_data.json"
ASSETS_PATH = "assets"
